# OPE: Problem Representation
This activity will allow you to practice with using NumPy and linear algebra for vectorization.

In this activity, you can assume that all indexings start at 0. In other words, the entries of a vector $x \in \mathbb{R}^n$ are $x_0, x_1, \ldots, x_{n-1}$.

In [1]:
import numpy as np

## Task 1:
### Learning Objectives
1. Search the NumPy library documentation to identify the desired function.
1. Apply elementwise vector operation in place of for-loops.

### Pretest
1. Which of the followings is the fastest way to create the NumPy array `[1, 2, 3, 4, ..., 9998, 9999]`?
    * `np.array(range(1, 10000))`
    * `np.array([i for i in range(1, 10000)])`
    * `np.arange(1, 10000)` (correct)
    * `np.range(1, 10000)`

1. Given two NumPy arrays `X` and `Y` (which may be multi-dimensional matrices), which of the following conditions is necessary to compute the sum `X + Y`?
    * `X` and `Y` have the same shape.
    * `X` and `Y` have the same shape after appropriate broadcasting. (correct)
    * `X` and `Y` have the same data type.
    * None of the above.


### Posttest
1. Which of the followings is the fastest way to create the NumPy array `[9999, 9998, 9997, 9996, ..., 2, 1]`?
    * `np.array(range(9999, 0, -1))`
    * `np.array([10000-i for i in range(1, 10000)])`
    * `np.arange(9999, 0, -1)` (correct)
    * `np.range(9999, 0, -1)`
    
1. Given two 2D NumPy arrays `X` and `Y`, which of the following conditions is necessary to compute the matrix product `X @ Y`?
    * `X` and `Y` have the same shape.
    * `X` and `Y` have the same data type.
    * `X.shape[0] == Y.shape[1]`
    * `X.shape[1] == Y.shape[0]` (correct)
    

### Coding assignment
In probability and statistics, the law of large number states that the average of the results obtained from a large number of trials will tend to become closer to the expected value as more trials are performed. Given a sequence of trial outcomes $x \in \mathbb R^n$, we can verify this theorem by computing the sequence of *cumulative averages*

\begin{align*}
s_0 & = x_0 \\
s_1 & = \frac{1}{2}(x_0 + x_1) \\
s_2 & = \frac{1}{3}(x_0 + x_1 + x_2) \\
\ldots \\
s_{n-1} & = \frac{1}{n} \sum_{i=0}^n x_i
\end{align*}

and examining its convergence property.

**Problem**:
Suppose you are given a sequence of trial outcomes $x \in \mathbb R^n$, implement the function `cumulative_avg` that computes the sequence of cumulative averages $s \in \mathbb{R}^n$, as defined above.

**Example**:
* Input:
```
x = [7, 2, 6, 4, 3, 8]
```
* Output:
```
s[0] = 7
s[1] = (7+2)/2 = 4.5
s[2] = (7+2+6)/3 = 5
s[3] = (7+2+6+4)/4 = 4.75
s[4] = (7+2+6+4+3)/5 = 4.4
s[5] = (7+2+6+4+3+8)/6 = 5
```

**Note**:
* You can only use functions from the Python standard library, NumPy or Scipy.
* Do not use any loop.

**Solution 1 (Using `np.cumsum`)**:

In [2]:
import numpy as np

def cumulative_avg(x):
    return np.cumsum(x) / np.arange(1, len(x) + 1)

x = np.array([7, 7, 7, 6, 0, 4, 0, 1, 0, 2])
cumulative_avg(x)

array([7.        , 7.        , 7.        , 6.75      , 5.4       ,
       5.16666667, 4.42857143, 4.        , 3.55555556, 3.4       ])

In [3]:
np.random.seed(1725)
x = np.random.randint(low = 12, high = 28, size = 10000)
cumulative_avg(x)

array([13.        , 15.5       , 17.33333333, ..., 19.54890978,
       19.54835484, 19.5488    ])

## Task 2:
### Learning Objectives
1. Apply the dot product in summing over the elements in a vector or matrix.
1. Subset elements from a list-like collection based on a given indexing pattern.

### Pretest
1. Given a 1D NumPy array `x`, which of the following operations is equivalent to `x.sum()`?
    * `x @ x.T`
    * `x.T @ x`
    * `x * np.ones(x.shape)`
    * `x.dot(np.ones(x.shape))` (correct)

1. Given `x = np.arange(10)`, what is the result of `x[2:9:3]`?
    * `[2, 9, 3]`
    * `[2, 5, 8]` (correct)
    * `[3, 5, 7]`
    * `[3, 2, 9]`

### Posttest
1. Given a 2D NumPy array `X`, which of the following operations is equivalent to `X.sum(axis = 0)`?
    * `X @ np.ones(X.shape[1])` (correct)
    * `X * np.ones(X.shape[1])`
    * `X.sum(axis = 1)`
    * `(X @ X.T).sum()`

1. Given `x = np.arange(15)`, what is the result of `x[1:10:4]`?
    * `[3, 4, 5]`
    * `[4, 5, 6]`
    * `[1, 10, 4]`
    * `[1, 5, 9]` (correct)

### Coding assignment
An important structure in calculus, which also has many uses in machine learning, is the alternating sum $\sum_i (-1)^i a_i$, where the entries alternate in sign between $1$ and $-1$. For example, you have likely seen the following Taylor expansion from a calculus class:
$$\sin x = \sum_{i=0}^\infty (-1)^i \frac{x^{2i+1}}{(2i+1)!}.$$
In this task, let's see how a general alternating sum can be vectorized.

**Problem**:

Given two vectors $x, y \in \mathbb{R}^n$, implement the function `alt_sum` that computes the following expression:
$$S = \sum_{i=0}^{n-1} (-1)^{i} x_i y_i = x_0y_0 - x_1y_1 + x_2y_2 - x_3y_3 + \ldots$$

**Example**:
* Input: `x = [2, 3, 5, 1], y = [9, 2, -2, 3]`
* Output: `2*9 - 3*2 + 5*(-2) - 1*3 = -1`.

**Note**:
* You can only use functions from the Python standard library, NumPy or Scipy.
* Do not use any loop.

**Solution 1 (Dot product with alternating 1s and -1s)**:

In [4]:
def alt_sum1(x, y):
    # construct the array [1, -1, 1, -1, 1, -1, ...]
    alt_plus_minus = np.resize([1, -1], len(x))
    return (x * y).dot(alt_plus_minus)

x, y = np.array([2, 3, 5, 1]), np.array([9, 2, -2, 3])
alt_sum1(x, y)

-1

In [5]:
type(np.array([1, 2, 3])) == np.ndarray

True

**Solution 2 (Slicing index)**:

In [6]:
def alt_sum2(x, y):
    n = len(x)
    # compute (x0y0 + x2y2 + x4y4 + ...) - (x1y1 + x3y3 + ...) 
    return x[::2].dot(y[::2]) - x[1::2].dot(y[1::2])

alt_sum2(x, y)

-1

In [7]:
low, high, size, seed = 30, 76, 2000, 899
np.random.seed(seed)
X = np.random.randint(low = low, high = high, size = (2, size))
print(alt_sum2(X[0], X[1]))

-11717


## Task 3

### Learning Objectives
1. Use one-hot encoding matrix as binary mask.
1. Subset elements with integer array indexing in multiple axes simultaneously.

### Pretest
1. Given `X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])` and `y = [2, 1, 2]`, let `Y` be the one-hot encoding of `y` with shape `3x4`. Which non-zero entries are present in the elementwise multiplication between `X` and `Y`?
     * `2, 5, 10`
     * `3, 6, 11`
     * `3, 7, 12`
     * `2, 1, 2`

1. Given a 2D NumPy array `X` with shape 10x10 and a matrix `Y = np.array([[2,5], [3,3], [1,2]]`, we want to construct a vector `v = np.array([X[2,5], X[3,3], X[1,2]])`. How may `v` be constructed from `X` and `Y`?
    * `X[Y[0], Y[1]]`
    * `X[Y[:,0], Y[:,1]]` (correct)
    * `X[Y, Y]`
    * `X[Y]`

### Posttest
1. Given `X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])` and `y = [0, 3, 3]`, let `Y` be the one-hot encoding of `y` with shape `3x4`. Which non-zero entries are present in the elementwise multiplication between `X` and `Y`?
    * 4, 7, 11
    * 1, 8, 12 (correct)
    * 1, 7, 11
    * 4, 5, 9

1. Given a 2D NumPy array `X` with shape 10x10 and a matrix `Y = np.array([2, 3, 1], [5, 3, 2])`, we want to construct a vector `v = np.array([X[2,5], X[3,3], X[1,2]])`. How may `v` be constructed from `X` and `Y`?
    * `X[Y[0], Y[1]]` (correct)
    * `X[Y[:,0], Y[:,1]]`
    * `X[Y, Y]`
    * `X[Y]`

### Coding Assignment
Assuming there are $k$ possible labels $\{0, 1, \ldots, k-1\}$, a logistic regression model can take an input data point $x \in \mathbb{R}^n$ and output a hypothesis vector $h \in \mathbb{R}^k$, where $h_j$ is the probability that the label of $x$ is $j$.

If the ground truth label of $x$ is also known (let's call it $y$), we can measure how good a model's prediction is by computing $\mathcal L(h, y) = -\log(h_y)$, which is called the *logistic loss*. For example, let's say there are two classes: 0 (dog) and 1 (cat). If the input data is a cat image (so $y = 1$), a model that outputs $h = (0.3, 0.7)$ would be better (have lower loss) than a model that outputs $h' = (0.5, 0.5)$, because 
$$-\log(h_y) = -\log(0.7) < -\log(0.5) = -\log(h'_y).$$

Typically there are not one but $n$ data points, so we can evaluate a model by computing its average loss across all data points. Let's implement this procedure.

**Problem**:

Assume you are given a hypothesis matrix $H \in \mathbb{R}^{n \times k}$, where each row $H_i$ is the hypothesis vector for the $i$-th data point, and a label vector $y \in \mathbb\{0, 1, \ldots, k-1\}^n$, where $y_i$ is the ground truth label of the $i$-th data point. Implement the function `logistic_loss` that computes the average logistic loss across all the data points:
$$L = -\frac{1}{n} \sum_{i=0}^{n-1} \log(H_{i,y_i}).$$

**Example**:
* Input: `H = [[0.1, 0.2, 0.7], [0.3, 0.4, 0.3], [0.5, 0.4, 0.1]], y = [1, 1, 0]`
* Output: 
```
    -1/3 * ( log(H[0,y[0]]) + log(H[1, y[1]]) + log(H[2, y[2]]) ) 
    = -1/3 * ( log(H[0,1]) + log(H[1,1]) + log(H[2,0]) )
    = -1/3 * ( log(0.2) + log(0.4) + log(0.5) )
    = 1.0729586
```


**Note**:
* You can only use functions from the Python standard library, NumPy or Scipy.
* Do not use any loop.

**Solution 1 (NumPy integer array indexing)**:

In [8]:
def logistic_loss1(H, y):
    n = len(y)
    return -np.log(H[np.arange(n), y]).sum() / n

H = np.array([[0.1, 0.2, 0.7], [0.3, 0.4, 0.3], [0.5, 0.4, 0.1]])
y = np.array([1, 1, 0])
logistic_loss1(H, y)

1.0729586082894003

**Solution 2 (One-hot encoding + Elementwise matrix mult)**:

In [9]:
def logistic_loss2(h, y):
    k, n = H.shape[1], len(y)
    Y_onehot = np.eye(k)[y]
    return -(np.log(H) * Y_onehot).sum() / n

logistic_loss2(H, y)

1.0729586082894003

In [10]:
low, high, row, col, seed = 1, 11, 1000, 2000, 432
np.random.seed(seed)
H = np.random.randint(low = low, high = high, size = (row, col)).astype(float)
H /= H.sum(axis = 1)[:,None]
y = np.random.choice(np.arange(H.shape[1]), size = H.shape[0])
output = logistic_loss1(H, y)
print(round(output, 4), output)

7.8231 7.82310281129308


## Task 4

### Learning Objectives
1. Construct multi-dimensional binary mask to extract elements from a matrix.
1. Subset elements with index slicing in multiple axes simultaneously.

### Pretest
1. Given a 2D NumPy array `X` with with `n` rows and `n` columns, we want to construct a matrix `Y` with the same shape, where `Y[i,j] = X[i,j] * (i == j)`. In other words, `Y` retains the elements in the main diagonal of `X` (e.g., `X[0,0], X[1,1]`) and transforms the rest to 0. Which of the following operations can construct `Y` from `X`?
    * `X[np.arange(n), np.arange(n)]`
    * `X @ np.eye(n)`
    * `X * np.eye(n)` (correct)
    * `np.diag(X)`

1. Given a 2D NumPy array `X` with `2*m` rows and `2*n` columns, we want to construct a matrix `Y` with `m` rows and `n` columns, where `Y[i, j] = X[2*i, 2*j]`. In other words, `Y` contains only the entries in `X` with even row and column indexes. Which of the following operations can construct `Y` from `X`?
    * `X[:2, :2]`
    * `X[::2, ::2]` (correct)
    * `X[np.arange(2*n), np.arange(2*n)]`
    * `X[np.arange(n)//2, np.arange(n)//2]`
    
### Posttest
1. Given a 2D NumPy array `X` with `n` rows and `n` columns, we want to construct a matrix `Y` with the same shape, where `Y[i, j] = X[i, j] * (i != j)`. In other words, `Y` transforms every element in the main diagonal of `X` (e.g., `X[0,0], X[1,1]`) to 0 and retains the rest. Which of the following operations can construct `Y` from `X`?
    * `X[np.arange(n), np.arange(n)]`
    * `X * (1 - np.eye(n))` (correct)
    * `1 - (X * np.eye(n))`
    * `1 - np.diag(X)`
    
1. Given a 2D NumPy array `X` with `2*m` rows and `2*n` columns, we want to construct a matrix `Y` with `m` rows and `n` columns, where `Y[i, j] = X[2*i+1, 2*j+1]`. In other words, `Y` contains only the entries in `X` with odd row and column indexes. Which of the following operations can construct `Y` from `X`?
    * `X[1::2, 1::2]` (correct)
    * `X[1:2, 1:2]`
    * `X[np.arange(2*n-1), np.arange(2*n-1)]`
    * `X[np.arange(n)//2, np.arange(n)//2]`

### Coding Assignment
While Numpy functions allow us to work on the entire input matrix, in many cases we only want to deal with a subset of the input (but still in a vectorized manner). Sometimes this is straightforward -- for example, getting the first 5 columns of `X` is just `X[,:5]`. Other times, the subset conditioning may be more involved. Let's see an example of this case.

**Problem**:

Given a matrix $X \in \mathbb{R}^{m \times n}$, implement the function `subset_sum` that computes the expression
$$S = \sum_{i=0}^{m-1} \sum_{j=0}^{n-1} \mathbb{1}(3 \mid i+j) \times X_{ij}.$$
where $\mathbb{1}(3 \mid i+j)$ returns $1$ if $i + j$ is divisible by $3$, and 0 otherwise. In other words, $S$ is the sum of all the entries $X_{ij}$ where $i+j$ is a multiple of 3. 

**Example**:
* Input: `X = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]`
* Output: `X[0,0] + X[0,3] + X[1,2] + X[2,1] = 1 + 4 + 7 + 10 = 22`

**Note**:
* You can only use functions from the Python standard library, NumPy or Scipy.
* Do not use any loop.

**Solution 1 (Binary matrix mask)**:

In [11]:
np.random.normal(size = (5, 3))

array([[-0.0266143 , -0.40868464, -1.84559579],
       [-0.74881028, -1.7035879 ,  1.27307924],
       [-0.30061987,  1.20460603, -0.2598243 ],
       [ 0.69729414,  1.4788428 ,  0.06015684],
       [ 0.66205409, -0.0668761 ,  0.47951586]])

In [12]:
def subset_sum1(X):
    m, n = X.shape
    mask = np.add.outer(np.arange(m), np.arange(n)) % 3 == 0
    return (X * mask).sum()

X = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
subset_sum1(X)

22

**Solution 2 (Slicing index)**:

In [13]:
def subset_sum2(X):
    return X[::3, ::3].sum() + X[1::3, 2::3].sum() + X[2::3, 1::3].sum()
    
subset_sum2(X)

22

In [14]:
low, high, row, col, seed = 17, 25, 5000, 100, 5555
np.random.seed(seed)
X = np.random.randint(low = low, high = high, size = (row, col))
print(subset_sum2(X))

3417536
